"""
Django settings for knights_of_climbalot project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

"""
We are using the django-allauth module to integrate various social media logins into the site.
To see what settings are necessary for django-allauth to work, see
http://goo.gl/QPKJFY
"""

'''
We are using the django-widget-tweaks add-on to modify form fields in the HTML with custom tags.
For more information about django-widget-tweaks, see
https://goo.gl/rCPU9U
'''


import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Base application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'climbalot',
    'widget_tweaks'
]

# Allauth apps.

INSTALLED_APPS += [
    # Django site's framework is required.
    'django.contrib.sites',
    # generic allauth apps that apply to all authentication using allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Specific allauth apps for various social providers. For more information see http://goo.gl/2VKRIt
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'knights_of_climbalot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Required by django-allauth template tags
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'knights_of_climbalot.wsgi.application'

# Authentication backends needed by django-allauth.
AUTHENTICATION_BACKENDS = [
    # Default backend - used to log into DJango admin by username.
    'django.contrib.auth.backends.ModelBackend',
    # Allauth specific authentication methods, such as login by e-mail.
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# You can customize date inputs, but you must turn USE_L10N off before they will stick, since L10N gets priority.
# L10N localizes date formats, but doesn't seem to do so very well (e.g. Pacific timezone is rendering dates as YYYY-mm-dd, which no one in pacific time uses).
DATE_INPUT_FORMATS = [
    '%m/%d/%Y', '%m/%d/%y'
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Login and Account requirements, as well as Login redirect.
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIAL_ACCOUNT_QUERY_EMAIL = True
LOGIN_REDIRECT_URL = "/"

# SECRET_KEY and Database information stored in secret_settings.py which is excluded from git through .gitignore.
# Import SECRET_KEY and Database information. Ensure that the secret_settings.py file is the correct one before using.

from .secret_settings import *
