# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='C_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellow', models.IntegerField(default=0)),
                ('green', models.IntegerField(default=0)),
                ('red', models.IntegerField(default=0)),
                ('blue', models.IntegerField(default=0)),
                ('orange', models.IntegerField(default=0)),
                ('purple', models.IntegerField(default=0)),
                ('black', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Monkey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name your monkey', max_length=25, verbose_name='monkey name')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('experience', models.IntegerField(validators=django.core.validators.MinValueValidator(0))),
                ('level', models.IntegerField(default=1, validators=django.core.validators.MinValueValidator(1))),
                ('main_color_grade', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('G', 'Green'), ('R', 'Red'), ('B', 'Blue'), ('O', 'Orange'), ('P', 'Purple'), ('K', 'Black')], max_length=1)),
                ('main_v_grade', models.CharField(blank=True, choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10')], max_length=3)),
                ('main_y_grade', models.CharField(blank=True, choices=[('5.7', '5.7'), ('5.8', (('5.8-', '5.8-'), ('5.8+', '5.8+'))), ('5.9', (('5.9-', '5.9-'), ('5.9+', '5.9+'))), ('5.10', (('5.10a', '5.10a'), ('5.10b', '5.10b'), ('5.10c', '5.10c'), ('5.10d', '5.10d'))), ('5.11', (('5.11a', '5.11a'), ('5.11b', '5.11b'), ('5.11c', '5.11c'), ('5.11d', '5.11d'))), ('5.12', (('5.12a', '5.12a'), ('5.12b', '5.12b'), ('5.12c', '5.12c'), ('5.12d', '5.12d')))], max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('c_value', models.CharField(blank=True, choices=[('Y', 'Yellow'), ('G', 'Green'), ('R', 'Red'), ('B', 'Blue'), ('O', 'Orange'), ('P', 'Purple'), ('K', 'Black')], max_length=1)),
                ('v_value', models.CharField(blank=True, choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10')], max_length=3)),
                ('y_value', models.CharField(blank=True, choices=[('5.7', '5.7'), ('5.8', (('5.8-', '5.8-'), ('5.8+', '5.8+'))), ('5.9', (('5.9-', '5.9-'), ('5.9+', '5.9+'))), ('5.10', (('5.10a', '5.10a'), ('5.10b', '5.10b'), ('5.10c', '5.10c'), ('5.10d', '5.10d'))), ('5.11', (('5.11a', '5.11a'), ('5.11b', '5.11b'), ('5.11c', '5.11c'), ('5.11d', '5.11d'))), ('5.12', (('5.12a', '5.12a'), ('5.12b', '5.12b'), ('5.12c', '5.12c'), ('5.12d', '5.12d')))], max_length=5)),
                ('attempts_total', models.IntegerField(default=0)),
                ('days_open', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Completed'), ('F', 'Failed')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('extra_points', models.IntegerField(blank=True, default=0, null=True)),
                ('workout', models.BooleanField(default=False)),
                ('quest_one_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('quest_two_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('quest_three_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('session_exp', models.IntegerField(default=0)),
                ('c_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.C_Routes')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbalot.Gym')),
                ('monkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climbalot.Monkey')),
                ('quest_one_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_one', to='climbalot.Quest')),
                ('quest_three_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_three', to='climbalot.Quest')),
                ('quest_two_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_two', to='climbalot.Quest')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='V_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.IntegerField(default=0)),
                ('v2', models.IntegerField(default=0)),
                ('v3', models.IntegerField(default=0)),
                ('v4', models.IntegerField(default=0)),
                ('v5', models.IntegerField(default=0)),
                ('v6', models.IntegerField(default=0)),
                ('v7', models.IntegerField(default=0)),
                ('v8', models.IntegerField(default=0)),
                ('v9', models.IntegerField(default=0)),
                ('v10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Y_Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c5_7', models.IntegerField(default=0)),
                ('c5_8_neg', models.IntegerField(default=0)),
                ('c5_8_pos', models.IntegerField(default=0)),
                ('c5_9_neg', models.IntegerField(default=0)),
                ('c5_9_pos', models.IntegerField(default=0)),
                ('c5_10_a', models.IntegerField(default=0)),
                ('c5_10_b', models.IntegerField(default=0)),
                ('c5_10_c', models.IntegerField(default=0)),
                ('c5_10_d', models.IntegerField(default=0)),
                ('c5_11_a', models.IntegerField(default=0)),
                ('c5_11_b', models.IntegerField(default=0)),
                ('c5_11_c', models.IntegerField(default=0)),
                ('c5_11_d', models.IntegerField(default=0)),
                ('c5_12_a', models.IntegerField(default=0)),
                ('c5_12_b', models.IntegerField(default=0)),
                ('c5_12_c', models.IntegerField(default=0)),
                ('c5_12_d', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='v_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.V_Routes'),
        ),
        migrations.AddField(
            model_name='session',
            name='y_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.Y_Routes'),
        ),
    ]
