# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monkey',
            name='experience',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monkey',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
