# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0004_auto_20160817_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='extra_points',
        ),
        migrations.AlterField(
            model_name='session',
            name='c_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.C_Routes'),
        ),
        migrations.AlterField(
            model_name='session',
            name='v_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.V_Routes'),
        ),
        migrations.AlterField(
            model_name='session',
            name='y_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.Y_Routes'),
        ),
    ]
