# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0005_auto_20160817_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='c_entry',
        ),
        migrations.RemoveField(
            model_name='session',
            name='v_entry',
        ),
        migrations.RemoveField(
            model_name='session',
            name='y_entry',
        ),
        migrations.AddField(
            model_name='c_routes',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.Session'),
        ),
    ]
