# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0006_auto_20160817_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='v_routes',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.Session'),
        ),
        migrations.AddField(
            model_name='y_routes',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climbalot.Session'),
        ),
    ]
