# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0010_monkey_crest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monkey',
            name='crest',
        ),
    ]
