# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0012_monkey_crest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(),
        ),
    ]
