# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0016_auto_20160825_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monkey',
            name='main_color_grade',
            field=models.CharField(blank=True, choices=[('Y', 'Yellow'), ('G', 'Green'), ('R', 'Red'), ('B', 'Blue'), ('O', 'Orange'), ('P', 'Purple'), ('K', 'Black')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='monkey',
            name='main_v_grade',
            field=models.CharField(blank=True, choices=[('V1', 'V1'), ('V2', 'V2'), ('V3', 'V3'), ('V4', 'V4'), ('V5', 'V5'), ('V6', 'V6'), ('V7', 'V7'), ('V8', 'V8'), ('V9', 'V9'), ('V10', 'V10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='monkey',
            name='main_y_grade',
            field=models.CharField(blank=True, choices=[('5.7', '5.7'), ('5.8', (('5.8-', '5.8-'), ('5.8+', '5.8+'))), ('5.9', (('5.9-', '5.9-'), ('5.9+', '5.9+'))), ('5.10', (('5.10a', '5.10a'), ('5.10b', '5.10b'), ('5.10c', '5.10c'), ('5.10d', '5.10d'))), ('5.11', (('5.11a', '5.11a'), ('5.11b', '5.11b'), ('5.11c', '5.11c'), ('5.11d', '5.11d'))), ('5.12', (('5.12a', '5.12a'), ('5.12b', '5.12b'), ('5.12c', '5.12c'), ('5.12d', '5.12d')))], max_length=5, null=True),
        ),
    ]
