# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0017_auto_20160825_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monkey',
            name='crest',
            field=models.ImageField(blank=True, null=True, upload_to='crests/'),
        ),
    ]
