# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0018_auto_20160825_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='monkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='climbalot.Monkey'),
        ),
    ]
