# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbalot', '0022_auto_20160830_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monkey',
            name='name',
            field=models.CharField(help_text='Name your monkey', max_length=25, unique=True, verbose_name='monkey name'),
        ),
    ]
